openapi: 3.0.1
info: 
  description: | 
    These are API for the app WASAPhoto, the application for the 
    2023/24 WASA Course.
  title: WASAPhoto
  version: 1.0.0

# Global application of the bearer authorization 
security:
  - Authorization: []

# Components definition
components:
  # Definition of the Bearer Auth used
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  # Definition of the schemas
  schemas:
    # User object
    User:
      title: "User"
      description: "This object represents a single user on WASAPhoto"
      type: object
      properties:
        username: 
          description: |
            Username of the user, can be changed
            Identifies a single user
            It can't contain spaces
          type: string
          pattern: '^.*?$'
          minLength: 3
          maxLength: 16
          example: "MarioRossi"
    # Post object
    Post:
      title: "Post"
      description: "This object represents a single post by a user"
      type: object
      properties:
        id:
          description: "Identifies a single post"
          type: number
          example: 1
        description:
          description: "The description of a post"
          type: string
          example: "Me at the zoo"
          
        
      
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody: 
        description: User details
        content:
          application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: "MarioRossi"
                    pattern: '^.*?$'
                    minLength: 3
                    maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
        
      
      